### ISSUE TITLE
Index Out of Range Exceptions

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#246]
Started getting this error with the 7.0.0.0 version

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MarkMpn.Sql4Cds.Autocomplete.GetSuggestions(String text, Int32 pos)
   at MarkMpn.Sql4Cds.SqlQueryControl.<>c__DisplayClass56_0.<CreateSqlEditor>b__3(Object s, DwellEventArgs e)
   at ScintillaNET.Scintilla.OnDwellStart(DwellEventArgs e)
   at ScintillaNET.Scintilla.WmReflectNotify(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

---
- Deployment: Online
- DB Version: 9.2.22084.202
- Connection Controls Version: 1.2022.7.53
- XrmToolBox Version: 1.2022.5.56
- Tool Version: 7.0.0.0

**Comment by MarkMpn** [comment]
Yep, fix will be incoming shortly. It's safe to just click Continue when it pops up for now.

**Comment by MarkMpn** [comment]
This should be fixed in 7.0.1, please reopen if you still get the error.
