### ISSUE TITLE
Crash when consumed from FXB

### ISSUE THREAD

**Issue by rappen** [MarkMpn/Sql4Cds#3]
Always getting this error, params seem to be correct.

```
An unexpected error occured: System.ArgumentNullException: Value cannot be null.

Parameter name: source

   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at MarkMpn.Sql4Cds.FetchXml2Sql.BuildJoins(AttributeMetadataCache metadata, TableReference dataSource, NamedTableReference parentTable, Object[] items, QuerySpecification query, IDictionary`2 aliasToLogicalName)
   at MarkMpn.Sql4Cds.FetchXml2Sql.BuildJoins(AttributeMetadataCache metadata, TableReference dataSource, NamedTableReference parentTable, Object[] items, QuerySpecification query, IDictionary`2 aliasToLogicalName)
   at MarkMpn.Sql4Cds.FetchXml2Sql.Convert(AttributeMetadataCache metadata, FetchType fetch)
   at MarkMpn.Sql4Cds.PluginControl.OnIncomingMessage(MessageBusEventArgs message)
   at XrmToolBox.New.PluginForm.SendIncomingBrokerMessage(MessageBusEventArgs message)
   at XrmToolBox.New.NewForm.MainForm_MessageBroker(Object sender, MessageBusEventArgs message)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.GetSQLQuery(Boolean& sql4cds)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.UpdateLiveXML(Boolean preventxmlupdate)
   at Cinteros.Xrm.FetchXmlBuilder.DockControls.XmlContentControl.XmlContentDisplayDialog_VisibleChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetVisible()
   at WeifenLuo.WinFormsUI.Docking.DockPane.set_ActiveContent(IDockContent value)
   at WeifenLuo.WinFormsUI.Docking.DockPane.ValidateActiveContent()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockState(DockState value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.ShowContentControl(XmlContentControl& control, ContentType contenttype, SaveFormat save, DockState state)
   at Cinteros.Xrm.FetchXmlBuilder.FetchXmlBuilder.tsmiShowSQL_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at XrmToolBox.Program.Main(String[] args)
```

**Comment by rappen** [comment]
Same when clicking the "Edit in SQL4CDS" button.
Version 1.0.4.0

**Comment by MarkMpn** [comment]
I think this was fixed in a later version, can you try updating to 1.0.9? If it still happens, can you share your FetchXML that this happens with please?

**Comment by rappen** [comment]
For some reason I'm not prompted to update, so I thought I had the latest version.
Noticing that version format was changed from four parts (1.0.4.0) to three parts (1.0.9) - perhaps that could be why? Ping @mscrmtools.

After update the error did not occur.

**Comment by MscrmTools** [comment]
Did you ask not to be prompted anymore for an update of this specific tool?

**Comment by rappen** [comment]
Nope.... Is that even possible?
