### ISSUE TITLE
Method missing : 'Int32 Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_RecommendedDegreesOfParallelism()'

### ISSUE THREAD

**Issue by jpp-laposte** [MarkMpn/Sql4Cds#317]
Hi,

I use  package nuget : id="MarkMpn.Sql4Cds.Engine" version="7.3.0" targetFramework="net462"

When I execute this code :
```
        internal static void SetDataFromOrganisation(string connectionString)
        {
            using (var con = new Sql4CdsConnection(connectionString))
            using (var cmd = con.CreateCommand())
            {
                cmd.CommandText = "UPDATE organization SET isfolderbasedtrackingenabled = 1, emailcorrelationenabled = 1";
                cmd.ExecuteNonQuery();
            }
        }
```

I have the following error message :
_Méthode introuvable : 'Int32 Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_RecommendedDegreesOfParallelism()'._

Here the stack trace :

```
Stack trace : 
   at MarkMpn.Sql4Cds.Engine.ExecutionPlan.ParallelismHelper.GetMaxDOP(DataSource dataSource, NodeCompilationContext context, IList`1 queryHints)
   at MarkMpn.Sql4Cds.Engine.ExecutionPlan.BaseDmlNode.GetMaxDOP(NodeCompilationContext context, IList`1 queryHints)
   at MarkMpn.Sql4Cds.Engine.ExecutionPlan.BaseDmlNode.FoldQuery(NodeCompilationContext context, IList`1 hints)
   at MarkMpn.Sql4Cds.Engine.ExecutionPlanOptimizer.Optimize(IRootExecutionPlanNodeInternal node, IList`1 hints)
   at MarkMpn.Sql4Cds.Engine.ExecutionPlanBuilder.ConvertStatement(TSqlStatement statement, ExecutionPlanOptimizer optimizer, List`1 queries)
   at MarkMpn.Sql4Cds.Engine.ExecutionPlanBuilder.Build(String sql, IDictionary`2 parameters, Boolean& useTDSEndpointDirectly)
   at MarkMpn.Sql4Cds.Engine.Sql4CdsCommand.GeneratePlan(Boolean compileForExecution)
   at MarkMpn.Sql4Cds.Engine.Sql4CdsCommand.Prepare()
   at MarkMpn.Sql4Cds.Engine.Sql4CdsCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at MarkMpn.Sql4Cds.Engine.Sql4CdsCommand.ExecuteNonQuery()
```

Regards
Sybaris

**Comment by MarkMpn** [comment]
Looks like I need to update the minimum version of the `Microsoft.CrmSdk.XrmTooling.CoreAssembly` package - at the moment it's pulling in version 9.1.0.79 but is actually expecting version 9.1.1.1 or later. If you add a reference to a more recent version of this package directly from your package this should resolve this error until I can release an update with a corrected dependency.
