### ISSUE TITLE
Error on Install of 8.0

### ISSUE THREAD

**Issue by daryllabar** [MarkMpn/Sql4Cds#404]
Maybe this is just me.  I had issues with the upgrade, so I uninstalled the the tool and then manually deleted the sub folder.  On install i got this error:

![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/30789a26-6f8a-4f3f-859f-ef8ee9c7c81a)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Could not load file or assembly 'file:///c:\users\daryllabar\appdata\roaming\mscrmtools\xrmtoolbox\plugins\MARKMPN.SQL4CDS\MarkMpn.Sql4Cds.XTB.dll' or one of its dependencies. The system cannot find the file specified.

Resulting in: The type initializer for 'MarkMpn.Sql4Cds.Plugin' threw an exception.

Resulting in: An exception occurred while trying to create an instance of type 'MarkMpn.Sql4Cds.Plugin'.

Resulting in: Cannot activate part 'MarkMpn.Sql4Cds.Plugin'.
Element: MarkMpn.Sql4Cds.Plugin -->  MarkMpn.Sql4Cds.Plugin -->  DirectoryCatalog (Path="C:\Users\DarylLaBar\AppData\Roaming\MscrmTools\XrmToolBox\Plugins")

Resulting in: Cannot get export 'MarkMpn.Sql4Cds.Plugin (ContractName="XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin")' from part 'MarkMpn.Sql4Cds.Plugin'.
Element: MarkMpn.Sql4Cds.Plugin (ContractName="XrmToolBox.Extensibility.Interfaces.IXrmToolBoxPlugin") -->  MarkMpn.Sql4Cds.Plugin -->  DirectoryCatalog (Path="C:\Users\DarylLaBar\AppData\Roaming\MscrmTools\XrmToolBox\Plugins")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at XrmToolBox.Extensibility.Manifest.ManifestLoader.<>c.<CreateManifest>b__4_0(Lazy`2 p)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()

```

So I restarted the XTB and now I get the error on start of the XTB.

**Comment by daryllabar** [comment]
After looking at this, it appears that all dlls in the lib\net452\Plugins\MarkMpn.Sql4Cds nuget folder are getting put in the plugin root directory.  I deleted the dlls and manually deployed the files from the nuget, and now I'm getting this error on load:
![image](https://github.com/MarkMpn/Sql4Cds/assets/9728423/faac4c31-6cbf-4f35-855f-111717883a7b)

**Comment by daryllabar** [comment]
And now to add to the mystery, if I run a local version of the XTB, it works... For now, it may just be something I dorked up on my machine.
