### ISSUE TITLE
[Exception] System.ArgumentNullException: Value cannot be null. Parameter name: String during FetchXMLBuilder parsing to SQL4CDS

### ISSUE THREAD

**Issue by rafek1241** [MarkMpn/Sql4Cds#64]
```
************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at MarkMpn.Sql4Cds.Engine.FetchXml2Sql.GetCondition(IOrganizationService org, IAttributeMetadataCache metadata, condition condition, String prefix, IDictionary`2 aliasToLogicalName, FetchXml2SqlOptions options, IDictionary`2 ctes, IDictionary`2 parameters, Boolean& requiresTimeZone, Boolean& usesToday)
   at MarkMpn.Sql4Cds.Engine.FetchXml2Sql.GetFilter(IOrganizationService org, IAttributeMetadataCache metadata, filter filter, String prefix, IDictionary`2 aliasToLogicalName, FetchXml2SqlOptions options, IDictionary`2 ctes, IDictionary`2 parameters, Boolean& requiresTimeZone, Boolean& usesToday)
   at MarkMpn.Sql4Cds.Engine.FetchXml2Sql.GetFilter(IOrganizationService org, IAttributeMetadataCache metadata, Object[] items, String prefix, IDictionary`2 aliasToLogicalName, FetchXml2SqlOptions options, IDictionary`2 ctes, IDictionary`2 parameters, Boolean& requiresTimeZone, Boolean& usesToday)
   at MarkMpn.Sql4Cds.Engine.FetchXml2Sql.BuildJoins(IOrganizationService org, IAttributeMetadataCache metadata, TableReference dataSource, NamedTableReference parentTable, Object[] items, QuerySpecification query, IDictionary`2 aliasToLogicalName, Boolean nolock, FetchXml2SqlOptions options, IDictionary`2 ctes, IDictionary`2 parameters, Boolean& requiresTimeZone, Boolean& usesToday)
   at MarkMpn.Sql4Cds.Engine.FetchXml2Sql.Convert(IOrganizationService org, IAttributeMetadataCache metadata, FetchType fetch, FetchXml2SqlOptions options, IDictionary`2& parameterValues)
   at MarkMpn.Sql4Cds.PluginControl.OnIncomingMessage(MessageBusEventArgs message)
   at XrmToolBox.New.PluginForm.SendIncomingBrokerMessage(MessageBusEventArgs message)
   at XrmToolBox.New.NewForm.MainForm_MessageBroker(Object sender, MessageBusEventArgs message)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2021.2.45
    Win32 Version: 1.2021.2.45
    CodeBase: file:///C:/Program%20Files%20(x86)/XRM%20Toolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
```

It was during parsing from `fetchxmlbuilder` to `sql4cds`.

query:
```
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="true" >
  <entity name="policy" >
    <attribute name="id" />
    ...otherattributes...
    <order attribute="status" descending="false" />
    <order attribute="createdon" descending="true" />
    <filter type="and" >
      <condition attribute="startdate" operator="not-null" />
      ...other not-null checks...
      <condition attribute="status" operator="eq" value="1" />
      <filter type="or" >
        <condition attribute="something" operator="null" />
        <condition attribute="something" operator="eq" value="0" />
      </filter>
    </filter>
    <link-entity name="many-to-many-relationship-table" from="id" to="id" intersect="true" link-type="outer" >
      <link-entity name="external-table" from="ext-id" to="ext-id" link-type="outer" alias="au" />
    </link-entity>
    <link-entity name="contact" from="contactid" to="contact" link-type="inner" alias="contact" >
      <filter type="and" >
        <condition attribute="contact-type" operator="eq" value="1" />
      </filter>
      <link-entity name="other-name" from="contact" to="contactid" link-type="inner" alias="ad" />
    </link-entity>
    <link-entity name="concept" from="conceptid" to="concept" link-type="inner" alias="concept" >
      <attribute name="price" />
      <filter type="and" >
        <condition attribute="legalentity" operator="not-null" />
        ...other not-null conditions
      </filter>
    </link-entity>
    <filter type="and" >
      <condition entityname="au" attribute="ext-id" operator="null" />
    </filter>
  </entity>
</fetch>
```

**Comment by rafek1241** [comment]
@MarkMpn 
Thank you :). Good job 👍🏻
